[project]
name = "aslcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Medhansh Garg", email = "medhansh2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "onnxruntime>=1.27.0",
    "onnxruntime-gpu>=1.27.0",
    "opencv-python>=5.0.0.93",
    "rtmlib>=0.0.15",
]

[project.scripts]
aslcv = "aslcv:main"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"
