[project]
name = "aslcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Medhansh Garg", email = "medhansh2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.35",
    "nvidia-cublas==13.6.0.2",
    "nvidia-cuda-nvrtc==13.3.33",
    "nvidia-cuda-runtime==13.3.29",
    "nvidia-cudnn-cu13==9.24.0.43",
    "nvidia-cufft==12.3.0.29",
    "nvidia-curand==10.4.3.29",
    "nvidia-nvjitlink==13.3.33",
    "onnxruntime>=1.27.0",
    "onnxruntime-gpu>=1.27.0",
    "opencv-python>=5.0.0.93",
    "pyyaml>=6.0.3",
    "ruamel.yaml>=0.18",
    "rtmlib>=0.0.15",
    "spacy>=3.8.14",
    "click>=8.4.2",
    "huggingface-hub>=1.27.0",
]

[project.scripts]
aslcv = "aslcv:main"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
]
